source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from accounts.views import RegisterView, UserDetailView, Users_list, UserUpdateView, UserPasswordChangeView

app_name = 'accounts'


urlpatterns = [
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('users/', Users_list.as_view(), name='users_list'),
    path('profile/', UserUpdateView.as_view(), name='user_update_profile'),
    path('<int:pk>/password_change', UserPasswordChangeView.as_view(), name='password_change'),
]

source/api_v1/urls.py
from django.urls import path

from api_v1.views import add, get_csrf_token_view, subtract, multiply, divide, index

app_name = 'api_v1'

urlpatterns = [
    path('add/', add, name='numbers'),
    path('get_token/', get_csrf_token_view, name='get_token'),
    path('subtract/', subtract, name='subtract'),
    path('multiply/', multiply, name='multiply'),
    path('divide/', divide, name='divide'),
    path('index/', index, name='index'),
]

source/issue_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api_v1/', include('api_v1.urls')),
    path('', include('tracker_app.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/tracker_app/urls.py
from django.urls import path

from tracker_app.views import (
    Index,
    AddIssue,
    IssueView,
    IssueUpdate,
    IssueDelete,
    IndexProjects,
    ProjectView,
    ProjectCreate,
    ProjectUpdate,
    ProjectDelete, AddUserToProject,
)

app_name = 'tracker'

urlpatterns = [
    path('issues', Index.as_view(), name='index'),
    path('issue/<int:pk>', IssueView.as_view(), name='issue_view'),
    path('issue/<int:pk>/update/', IssueUpdate.as_view(), name='issue_update'),
    path('issue/<int:pk>/delete/', IssueDelete.as_view(), name='issue_delete'),
    path('', IndexProjects.as_view(), name='index_projects'),
    path('project/<int:pk>/', ProjectView.as_view(), name='project_View'),
    path('project/create/', ProjectCreate.as_view(), name='project_create'),
    path('project/<int:pk>/issue_create', AddIssue.as_view(), name='issue_create'),
    path('project/<int:pk>/update/', ProjectUpdate.as_view(), name='project_update'),
    path('project/<int:pk>/delete/', ProjectDelete.as_view(), name='project_delete'),
    path('project/<int:pk>/user_add/', AddUserToProject.as_view(), name='user_add'),
]

source/tracker_app/models.py
from django.conf import settings
from django.db import models

from tracker_app.validator import BadWordsValidation, capital_letter, MinLengthValidator

bad_words = ('fuck', 'bullshit', 'asshole')

# Create your models here.


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Issue(BaseModel):
    summary = models.CharField(max_length=50, null=False, blank=False, verbose_name='Заголовок',
                               validators=[BadWordsValidation(bad_words), capital_letter, MinLengthValidator(10)])
    description = models.CharField(max_length=1000, null=True, blank=True, verbose_name='Описание',
                                   validators=[BadWordsValidation(bad_words)])
    status = models.ForeignKey('tracker_app.Status', on_delete=models.PROTECT, max_length=50, verbose_name='Статус')
    type = models.ManyToManyField('tracker_app.Type', related_name='issues', blank=True, verbose_name='Тип')
    project = models.ForeignKey('tracker_app.Project', related_name='project_issues', on_delete=models.CASCADE,
                                verbose_name='Проект')

    class Meta:
        db_table = 'issues'
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    def __str__(self):
        return "{}. {}".format(self.pk, self.summary)


class Status(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False, verbose_name='Название')

    def __str__(self):
        return "{}".format(self.name)

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'


class Type(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False, verbose_name='Тип')

    def __str__(self):
        return "{}".format(self.name)

    class Meta:
        verbose_name = 'Тип'
        verbose_name_plural = 'Типы'


class Project(models.Model):
    start_time = models.DateField(null=False, blank=False)
    end_time = models.DateField(null=True, blank=True)
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    user = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        related_name='projects',
        verbose_name='Пользователь',
    )

    class Meta:
        permissions = [
            ('add_user_to_project', 'Добавить пользователя к проекту')
        ]

    def __str__(self):
        return "{}".format(self.title)

source/tracker_app/forms.py
from django import forms

from tracker_app.models import Issue, Project


class IssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ['summary', 'description', 'status', 'type']


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти")


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'start_time', 'end_time', 'description']


class AddUser(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['user']

source/tracker_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, TemplateView, ListView

# Create your views here.
from tracker_app.forms import IssueForm, SimpleSearchForm
from tracker_app.models import Issue, Project
from django.db.models import Q
from django.utils.http import urlencode

class Index_view(ListView):
    template_name = 'index_projects.html'
    context_object_name = 'projects'
    model = Project
    ordering = 'start_time'

class Index(ListView):
    template_name = 'index.html'
    context_object_name = 'issues'
    model = Issue
    ordering = ['-created_at']

    paginate_by = 3
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        context['search'] = self.search_value
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset


class AddIssue(View):

    def get(self, request, **kwargs):
        print(self.kwargs, request, kwargs)
        form = IssueForm()
        return render(request, 'issue_create.html', context={'form': form})

    def post(self, request, **kwargs):
        form = IssueForm(data=request.POST)
        if form.is_valid():
            issue = Issue.objects.create(
                summary=form.cleaned_data.get('summary'),
                description=form.cleaned_data.get('description'),
                status=form.cleaned_data.get('status'),
            )
            issue.type.set(form.cleaned_data.get('type'))
        else:
            return render(request, 'issue_create.html', context={'form': form})
        return redirect('issue_view', pk=issue.id)


class IssueView(TemplateView):
    template_name = 'issue_view.html'

    def get_context_data(self, **kwargs):
        issue = get_object_or_404(Issue, pk=kwargs['pk'])
        context = super().get_context_data()
        context['issue'] = issue
        return context


class IssueUpdate(TemplateView):
    template_name = 'issue_update.html'

    def get(self, request, **kwargs):
        print(self.kwargs, request, kwargs)
        issue = get_object_or_404(Issue, pk=kwargs['pk'])
        form = IssueForm(initial={
            'summary': issue.summary,
            'description': issue.description,
            'status': issue.status,
            'type': issue.type.all()
        })
        return render(request, 'issue_update.html', context={'form': form, "id": issue.id})

    def post(self, request, **kwargs):
        issue = get_object_or_404(Issue, pk=kwargs['pk'])
        form = IssueForm(data=request.POST)
        if form.is_valid():
            issue.summary = form.cleaned_data.get('summary')
            issue.description = form.cleaned_data.get('description')
            issue.status = form.cleaned_data.get('status')
            issue.type.set(form.cleaned_data.get('type'))

            issue.save()
        else:
            return render(request, 'issue_update.html', context={'form': form, "id": issue.id})
        return redirect('issue_view', pk=issue.id)


class IssueDelete(TemplateView):
    template_name = 'issue_delete.html'

    def get(self, request, **kwargs):
        issue = get_object_or_404(Issue, pk=kwargs.get("pk"))
        return render(request, 'issue_delete.html', context={'issue': issue})

    def post(self, request, **kwargs):
        issue = get_object_or_404(Issue, pk=kwargs.get("pk"))
        issue.delete()
        return redirect('index')

source/tracker_app/views/issues.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView

# Create your views here.
from tracker_app.forms import IssueForm, SimpleSearchForm
from tracker_app.models import Issue, Project
from django.db.models import Q
from django.utils.http import urlencode


class Index(ListView):
    template_name = 'issues/index.html'
    context_object_name = 'issues'
    model = Issue
    ordering = ['-created_at']

    paginate_by = 3
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        context['search'] = self.search_value
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset


class AddIssue(PermissionRequiredMixin, CreateView):
    model = Issue
    template_name = 'issues/issue_create.html'
    form_class = IssueForm
    permission_required = 'tracker_app.add_issue'


    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        issue = form.save(commit=False)
        issue.project = project
        issue.save()
        form.save_m2m()
        return redirect('tracker:project_View', pk=project.pk)

    def has_permission(self):
        return super().has_permission() and self.request.user in Project.objects.get(pk=self.kwargs.get('pk')).user.all()


class IssueView(TemplateView):

    template_name = 'issues/issue_view.html'

    def get_context_data(self, **kwargs):
        issue = get_object_or_404(Issue, pk=kwargs['pk'])
        context = super().get_context_data()
        context['issue'] = issue
        return context


class IssueUpdate(PermissionRequiredMixin, UpdateView):
    model = Issue
    template_name = 'issues/issue_update.html'
    form_class = IssueForm
    context_object_name = 'issue'
    permission_required = 'tracker_app.change_issue'

    def get_success_url(self):
        return reverse('tracker:issue_view', kwargs={'pk': self.object.pk})

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().project.user.all()


class IssueDelete(PermissionRequiredMixin, DeleteView):
    template_name = 'issues/issue_delete.html'
    model = Issue
    context_object_name = 'issue'
    success_url = reverse_lazy('tracker:index')
    permission_required = 'tracker_app.delete_issue'

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().project.user.all()

source/tracker_app/views/projects.py
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from tracker_app.forms import ProjectForm, AddUser
from tracker_app.models import Project
from django.contrib.auth.mixins import PermissionRequiredMixin


class IndexProjects(ListView):
    template_name = 'projects/index_projects.html'
    context_object_name = 'projects'
    model = Project
    ordering = 'start_time'


class ProjectView(DetailView):
    template_name = 'projects/project_view.html'
    model = Project
    context_object_name = 'project'


class ProjectCreate(PermissionRequiredMixin, CreateView):
    template_name = 'projects/project_create.html'
    model = Project
    form_class = ProjectForm
    permission_required = 'tracker_app.add_project'

    def form_valid(self, form):
        project = form.save()
        project.user.add(self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('tracker:project_View', kwargs={'pk': self.object.pk})


class ProjectUpdate(PermissionRequiredMixin, UpdateView):
    model = Project
    template_name = 'projects/project_update.html'
    form_class = ProjectForm
    context_object_name = 'project'
    permission_required = 'tracker_app.change_project'

    def get_success_url(self):
        return reverse('tracker:project_View', kwargs={'pk': self.object.pk})


class ProjectDelete(PermissionRequiredMixin, DeleteView):
    model = Project
    template_name = 'projects/project_delete.html'
    context_object_name = 'project'
    success_url = reverse_lazy('tracker:index_projects')
    permission_required = 'tracker_app.delete_project'


class AddUserToProject(PermissionRequiredMixin, UpdateView):
    model = Project
    template_name = 'users/add_user.html'
    form_class = AddUser
    context_object_name = 'project'
    permission_required = 'tracker_app.add_user_to_project'

    def get_success_url(self):
        return reverse('tracker:project_View', kwargs={'pk': self.object.pk})

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().user.all()

source/tracker_app/templates/projects/index_projects.html
{% extends 'base.html' %}
<div class="background-main">
{% block menu %}

    <li><a href="{% url 'tracker:project_create' %}">Create project</a></li>
    <li><a href="{% url 'tracker:index' %}">Issues</a></li>

{% endblock %}


{% block content %}
    <div class=".bg-light">
        <h1 class="main_title title-project-main">Проекты</h1>
    {% include 'partial/project_list.html' %}
    </div>

{% endblock %}
</div>

source/tracker_app/templates/projects/project_create.html
{% extends "base.html" %}
{% block title %}Create project{% endblock %}

{% block content %}
    <div>
        <h1>Create project</h1>
        <form method="post" action="{% url "tracker:project_create" %}">
            {% include "partial/form.html" with button_text="Create" %}
        </form>
    </div>
{% endblock %}

source/tracker_app/templates/projects/project_delete.html
{% extends 'base.html' %}

{% block title %}Подтвердите удаление проекта{% endblock %}
{% block page_header %}Вы уверены, что хотите удалить проект {{ project.title }}?{% endblock page_header %}

{% block content%}
    <form action="{% url "tracker:project_delete" project.id %}" method="POST">
        {% include 'partial/form.html' with button_text="Конечно я хочу удалить проект" %}
        <a href="{% url "tracker:project_View" project.id %}">Нее, передумал что-то</a>
    </form>
{% endblock content %}

source/tracker_app/templates/projects/project_update.html
{% extends "base.html" %}
{% block title %}Update project{% endblock %}
{% block menu %}
    <li><a href="{% url 'tracker:project_View' project.id %}">Back</a></li>
{% endblock %}
{% block content %}
    <div>
        <h1>Update project</h1>

        <form method="post" action="{% url "tracker:project_update" project.pk %}">
            {% include "partial/form.html" with button_text="Update" %}
        </form>
    </div>
{% endblock %}

source/tracker_app/templates/projects/project_view.html
{% extends 'base.html' %}


{% block menu %}
    {% if perms.tracker_app.add_issue and request.user in project.user.all %}
    <li><a href="{% url 'tracker:issue_create' project.pk %}">Create issue</a></li>
    {% endif %}
    <li><a href="{% url 'tracker:project_update' project.pk %}">Project update</a></li>
    {% if perms.tracker_app.delete_project %}
    <li><a href="{% url 'tracker:project_delete' project.pk %}">Project delete</a></li>
    {% endif %}
    {% if perms.auth.add_user %}
    <li><a href="{% url 'tracker:user_add' project.pk %}">Add user</a></li>
    {% endif %}
{% endblock menu %}

{% block title %}{{ project.title }}{% endblock %}



<{% block content %}

<div class="guest_card card border-dark mt-5" style="max-width: 18rem;">
      <div class="card-header">
          <span>{{ project.title }}</span>
      </div>
      <div class="card-body text-dark">
        <h5 class="card-title"></h5>
            <p class="card-text">Дата начала : {{ project.start_time }}</p>
            <p>Дата окончания: {{ project.end_time }}</p>
            {% if project.description %}
                <p class="card-text">Описание : {{ project.description }}</p>
            {% else %}
                <p class="card-text">Описание не указано</p>
            {% endif %}
            {% if project.user.all%}
                <p class="card-text">Пользователи этого проекта:</p>
            {% endif %}
            {% for user in project.user.all %}
                <a href="{% url 'accounts:detail' user.pk %}" class="card-project-inner">{{ user.username }}</a>
            {% endfor %}
            <div>
                {% for issue in project.project_issues.all %}
                <div class="guest_card card border-dark mb-5" style="max-width: 18rem;">
                    <div class="card-header">
                        <span><a href="{% url 'tracker:issue_view' issue.pk %}">{{ issue.summary }}</a></span>
                    </div>
                    <div class="card-body text-dark">
                    <h5 class="card-title"></h5>
                    <p class="card-text">Статус : {{ issue.status }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>

      </div>
</div>
{% endblock %}