source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from accounts.views import RegisterView, UserDetailView, Users_list, UserUpdateView, UserPasswordChangeView

app_name = 'accounts'


urlpatterns = [
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('users/', Users_list.as_view(), name='users_list'),
    path('profile/', UserUpdateView.as_view(), name='user_update_profile'),
    path('<int:pk>/password_change', UserPasswordChangeView.as_view(), name='password_change'),
]

source/api_v1/urls.py
from django.urls import path

from api_v1.views import add, get_csrf_token_view, subtract, multiply, divide, index

app_name = 'api_v1'

urlpatterns = [
    path('add/', add, name='numbers'),
    path('get_token/', get_csrf_token_view, name='get_token'),
    path('subtract/', subtract, name='subtract'),
    path('multiply/', multiply, name='multiply'),
    path('divide/', divide, name='divide'),
    path('index/', index, name='index'),
]

source/issue_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api_v1/', include('api_v1.urls')),
    path('', include('tracker_app.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models


# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(
        get_user_model(),
        on_delete=models.CASCADE,
        verbose_name='Профиль пользователя',
        related_name='profile',
    )
    birth_date = models.DateField(
        null=True,
        blank=True,
        verbose_name='Дата рождения',
    )
    avatar = models.ImageField(
        upload_to='avatars',
        null=True,
        blank=True,
        verbose_name='Аватар'
    )
    github_profile = models.URLField(max_length=500, null=True, blank=True)
    about_me = models.TextField(max_length=1000, null=True, blank=True)

    def __str__(self):
        return self.user.username

    class Meta:
        db_table = 'profiles'
        verbose_name = 'Профиль пользователя'
        verbose_name_plural = 'Профили пользователей'
        permissions = [
            ('can_view_users_list', 'Может просматривать пользователей')
        ]

source/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm


from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm, UsernameField

from accounts.models import Profile


class MyUserCreationForm(UserCreationForm):
    email = forms.CharField(required=True)

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get("first_name")
        last_name = cleaned_data.get("last_name")
        if not first_name and not last_name:
            raise forms.ValidationError('Please fill in these fields')

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2',
                  'first_name', 'last_name', 'email']
        field_classes = {'username': UsernameField}


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name',)


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth import login, get_user_model, update_session_auth_hash
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from .forms import MyUserCreationForm, UserUpdateForm, ProfileUpdateForm, PasswordChangeForm


# Create your views here.
from .models import Profile


class RegisterView(CreateView):
    model = User
    template_name = 'registration/user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('tracker:index_projects')
        return next_url


class UserDetailView(DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    paginate_related_by = 5
    paginate_related_orphans = 0

    def get_context_data(self, **kwargs):
        projects = self.get_object().projects.all()
        paginator = Paginator(projects, self.paginate_related_by, orphans=self.paginate_related_orphans)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        kwargs['page_obj'] = page
        kwargs['projects'] = page.object_list
        kwargs['is_paginated'] = page.has_other_pages()
        return super().get_context_data(**kwargs)


class Users_list(PermissionRequiredMixin, ListView):
    model = get_user_model()
    template_name = 'users_list.html'
    context_object_name = 'users'
    ordering = 'username'
    permission_required = 'accounts.can_view_users_list'


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserUpdateForm
    context_object_name = 'user_obj'
    template_name = 'user_change.html'
    profile_form_class = ProfileUpdateForm

    def get_object(self, queryset=None):
        return self.request.user

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        context['profile_form'] = kwargs.get('profile_form')
        if context['profile_form'] is None:
            context['profile_form'] = self.get_profile_form()
        return context

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES

        return self.profile_form_class(**form_kwargs)

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})

source/accounts/templates/login.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
         content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Вход</title>
</head>
<body>

<div class="container">
    <h1>Вход</h1>

    <form action="{% url 'login' %}" method="post" class="text-center">
        {% csrf_token %}
        {% if has_error %}
            <p class="form-error">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" name="password" id="password">
        </div>
        <button type="submit">Войти</button>
    </form>

</div>

</body>
</html>

source/accounts/templates/user_change.html
{% extends 'base.html' %}


{% block title %}Редактировать профиль{% endblock %}
{% block menu_links %}
    <li><a href="{% url "accounts:detail" user_obj.pk %}">Назад</a></li>
    <li><a href="{% url "accounts:password_change" user_obj.pk %}">Смена пароля</a></li>
{% endblock %}

{% block content %}
    <h1>Поменять личные данные</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partial/form.html' with form=form fields_only=True %}
        {% include 'partial/form.html' with form=profile_form fields_only=True %}
        <br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}


{% block title %}Пользователь{% endblock %}


{% block menu_links %}
    {% if request.user == user_obj %}
    <li><a href="{% url 'accounts:user_update_profile' %}">Редактировать</a></li>
    <li><a href="{% url "accounts:password_change" user_obj.pk %}">Смена пароля</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>
    {% if user_obj.profile.avatar %}
        <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="250" height="250" alt="user picture">
    {% endif %}
    <p>Имя пользователя: {{ user_obj.username }}</p>
    <p>Имя: {{ user_obj.first_name }}</p>
    <p>Фамилия: {{ user_obj.last_name }}</p>
    <p>Дата рождения: {{ user_obj.profile.birth_date|date:'d.m.Y' }}</p>
    <p>Почта: {{ user_obj.email }}</p>
    <p> Ссылка на GitHub : {{ user_obj.profile.github_profile }} </p>
    <p>Обо мне : {{ user_obj.profile.about_me }}</p>

    <h2 class="text-center clear">Проекты пользователя:</h2>
    {% include 'partial/project_list.html' %}

{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}


{% block title %}Смена пароля{% endblock %}


{% block menu_links %}
    <li><a href="{% url "accounts:detail" user_obj.pk %}">Назад</a></li>
    <li><a href="{% url "accounts:user_update_profile" %}">Редактирование личных данных</a></li>
{% endblock %}


{% block content %}
    <h1>Смена пароля</h1>
    {% url "accounts:password_change" user_obj.pk as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method="post" button_text='change' %}
{% endblock %}

source/accounts/templates/users_list.html
{% extends 'base.html' %}
{% block menu %}


{% endblock %}


{% block content %}
    <div class=".bg-light">
        <h1 class="main_title title-project-main">Users</h1>
        {% for user in users %}
        <div class="card text-dark bg-info mb-3" style="max-width: 18rem;">
        <div class="card-header"><h3><a href="{% url 'accounts:detail' user.pk %}" class="card-project-inner">{{ user.username }}</a></h3></div>
        <div class="card-body">
        <h5 class="card-title"></h5>
        <p class="card-text"></p>
        </div>
        </div>
        {% endfor %}

    </div>

{% endblock %}