source/api_v1/urls.py
from django.urls import path

from api_v1.views import add, get_csrf_token_view, subtract, multiply, divide, index

app_name = 'api_v1'

urlpatterns = [
    path('add/', add, name='numbers'),
    path('get_token/', get_csrf_token_view, name='get_token'),
    path('subtract/', subtract, name='subtract'),
    path('multiply/', multiply, name='multiply'),
    path('divide/', divide, name='divide'),
    path('index/', index, name='index'),
]

source/issue_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api_v1/', include('api_v1.urls')),
    path('', include('tracker_app.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/api_v1/models.py
from django.db import models

# Create your models here.

source/api_v1/views.py
import json

from django.core.serializers import serialize, deserialize
from django.http import HttpResponse, HttpResponseNotAllowed, JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import ensure_csrf_cookie

from tracker_app.models import Project


@ensure_csrf_cookie
def get_csrf_token_view(request):
    if request.method == 'GET':
        return HttpResponse(json.dumps({"token": "ok"}))
    return HttpResponse(status=405)


def add(request):
    if request.body:
        try:
            numbers_data = json.loads(request.body)
            print(numbers_data)
            if not numbers_data.get("A") or not numbers_data.get("B"):
                response_body = {
                    'error': "You haven`t entered anything!"
                }
                response = HttpResponse(json.dumps(response_body))
                response['content-type'] = 'application/json'
                response.status_code = 400
                return response
            answer = int(numbers_data['A']) + int(numbers_data['B'])
            response_body = {
                'answer': answer
            }
            response = HttpResponse(json.dumps(response_body))
            response['content-type'] = 'application/json'
        except:
            print('couldn`t convert')
            response_body = {
                'error': "Couldn`t convert to number :("
            }
            response = HttpResponse(json.dumps(response_body))
            response['content-type'] = 'application/json'
            response.status_code = 400
        return response


def subtract(request):
    if request.body:
        try:
            numbers_data = json.loads(request.body)
            answer = int(numbers_data['A']) - int(numbers_data['B'])
            response_body = {
                'answer': answer
            }
            response = HttpResponse(json.dumps(response_body))
            response['content-type'] = 'application/json'
        except ValueError:
            response_body = {
                'error': "Pls enter numbers"
            }
            response = HttpResponse(json.dumps(response_body))
            response['content-type'] = 'application/json'
            response.status_code = 400

        except BaseException:
            response_body = {
                'error': "Pls enter numbers"
            }
            response = HttpResponse(json.dumps(response_body))
            response['content-type'] = 'application/json'
            response.status_code = 400
        return response


def multiply(request):
    if request.body:
        try:
            numbers_data = json.loads(request.body)
            answer = int(numbers_data['A']) * int(numbers_data['B'])
            response_body = {
                'answer': answer
            }
            response = HttpResponse(json.dumps(response_body))
            response['content-type'] = 'application/json'
        except ValueError:
            response_body = {
                'error': "Pls enter some number"
            }
            response = HttpResponse(json.dumps(response_body))
            response['content-type'] = 'application/json'
            response.status_code = 400

        except BaseException:
            print('some error')
            response_body = {
                'error': "some error"
            }
            response = HttpResponse(json.dumps(response_body))
            response['content-type'] = 'application/json'
            response.status_code = 400
        return response


def divide(request):
    if request.body:
        try:
            numbers_data = json.loads(request.body)
            answer = int(numbers_data['A']) / int(numbers_data['B'])
            response_body = {
                'answer': answer
            }
            response = HttpResponse(json.dumps(response_body))
            response['content-type'] = 'application/json'
        except ValueError:
            print('Value error')
            response_body = {
                'error': "Pls enter some number"
            }
            response = HttpResponse(json.dumps(response_body))
            response['content-type'] = 'application/json'
            response.status_code = 400

        except ZeroDivisionError:
            print('zero error')
            response_body = {
                'error': "You cannot divide by zero!"
            }
            response = HttpResponse(json.dumps(response_body))
            response['content-type'] = 'application/json'
            response.status_code = 400
        return response


def index(request):
    return render(request, 'index.html')

source/api_v1/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://kit-free.fontawesome.com/releases/v5.11.1/css/free.min.css" media="all">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>
<body>

    <div class="container mt-5">
        <form>
            First number: <input type="text" id="FirstNumber"><br>
            Second number: <input type="text" id="SecondNumber"><br>
            <input data-url="{% url 'api_v1:numbers' %}" onclick="CalculateAction(event)" type="submit"  value="Add">
            <input data-url="{% url 'api_v1:subtract' %}" onclick="CalculateAction(event)" type="submit" value="Subtract">
            <input data-url="{% url 'api_v1:multiply' %}" onclick="CalculateAction(event)" type="submit" value="Multiply">
            <input data-url="{% url 'api_v1:divide' %}" onclick="CalculateAction(event)" type="submit" value="Divide">
        </form>

        <div id="print_result">


        </div>
    </div>




    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

    <script src="{% static 'js/calculations.js' %}">

    </script>
</body>
</html>